# Generated by Django 6.1.2 on 2026-10-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=100, unique=True)),
                ('request_digest', models.CharField(max_length=255)),
                ('serialized_result', models.JSONField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('event_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('COUNT', 'COUNT'), ('VOID', 'VOID')], max_length=10)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('target_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING_REFERENCE', 'PENDING_REFERENCE'), ('DUPLICATE', 'DUPLICATE'), ('CONFLICT', 'CONFLICT'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source_id', 'event_id')},
            },
        ),
    ]
